# Generated by Django 5.1.5 on 2025-02-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=100)),
                ('number_of_persons', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('transportation_method', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField(blank=True, null=True)),
                ('Cname', models.CharField(default='India', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=255)),
                ('altitude', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('includes', models.JSONField(default=list)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='location_images/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('backimage', models.ImageField(blank=True, null=True, upload_to='location_images/')),
            ],
        ),
    ]
